CREATE VIEW V_EMPLOYEE_PARTIAL_INFO
(NAME, MUSEUM, POSITION)
AS
SELECT E.NAME, E.MUSEUM_NAME AS MUSEUM, E.POSITION
FROM EMPLOYEE E
WHERE POSITION='Director'
ORDER BY MUSEUM;

CREATE VIEW V_EXHIBIT_TRANSPORT_INFO
(NAME, MUSEUM, EXHIBITION, ADDRESS, FLOOR, AUDITORIUM, CONDITION)
AS
SELECT E.NAME AS EXHIBIT, M.NAME AS MUSEUM, EXH.NAME AS EXHIBITION, M.ADDRESS, EXH.FLOOR, EXH.AUDITORIUM, E.CONDITION
FROM MUSEUM M JOIN EXHIBITION EXH on
M.NAME=EXH.MUSEUM_NAME JOIN 
EXHIBIT E ON EXH.NAME=E.EXHIBITION_NAME
ORDER BY E.NAME;

CREATE VIEW V_TICKET_INCOME
(NAME, TICKET_PRICE, VISITORS, TOTAL)
AS
SELECT V.MUSEUM_NAME AS MUSEUM,I.PRICE, SUM(V.VISITORS_COUNT) AS VISITORS,SUM(V.VISITORS_COUNT)*I.PRICE AS TOTAL
FROM ITEM I JOIN VISITORS V ON
I.MUSEUM_NAME = V.MUSEUM_NAME AND I.TYPE = 'ticket'
GROUP BY V.MUSEUM_NAME, I.PRICE;

CREATE VIEW V_MUSEUM_STATISTIC
(NAME, EXHIBIT_COUNT, EMPLOYEE_COUNT)
AS
SELECT M.NAME,SUM(E.EXHIBIT_COUNT) AS EXHIBIT_COUNT,M.EMPLOYEE AS EMPLOYEE_COUNT
FROM MUSEUM M JOIN EXHIBITION E ON
M.NAME = E.MUSEUM_NAME 
GROUP BY M.NAME, M.EMPLOYEE;

CREATE VIEW V_MAX_PAID_EMPLOYEE
(NAME, ADDRESS, SALARY, POSITION)
AS
SELECT M.NAME, M.ADDRESS, MAX(E.SALARY) AS MAX_SALORY,POSITION
FROM MUSEUM M JOIN EMPLOYEE E ON
M.NAME = E.MUSEUM_NAME 
GROUP BY M.NAME, M.ADDRESS,POSITION
ORDER BY MAX(SALARY) DESC;


